language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jsproject' ]; then cd .. && eval "mv $currentfolder generator-jsproject" && cd generator-jsproject; fi

